issues:
  exclude-rules:
    - path: main.go
      linters:
        - cyclop
      source: run
    - path: msgpack/msgpack.go
      linters:
        - cyclop
linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gci
    - mnd
    - intrange
    - lll
    - tenv
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  cyclop:
    skip-tests: true
  gomoddirectives:
    replace-local: true
    replace-allow-list:
      - "github.com/justenwalker/mack"
run:
  modules-download-mode: readonly
  go: '1.24'
output:
  formats:
    - format: checkstyle
      path: lint-report.checkstyle.xml
    - format: colored-line-number
      path: stdout
  sort-results: true
  sort-order:
    - file
    - linter
    - severity