issues:
  exclude:
    - 'Encoding is a global variable'
  exclude-rules:
    - { path: sensible/sensible.go, linters: [ gochecknoglobals ] }
    - { path: crypt/internal/, linters: [ gochecknoglobals ] }
    - { path: crypt/random/, linters: [ gochecknoglobals ] }
    - { path: internal/testhelpers/, linters: [ gochecknoglobals ] }
    - path: encoding/msgpack/
      linters:
        - cyclop
    - path: encoding/libmacaroon/
      linters:
        - cyclop
        - exhaustive
linters:
  enable-all: true
  disable:
    - copyloopvar
    - err113
    - execinquery
    - exhaustruct
    - funlen
    - gci
    - gomnd
    - intrange
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  cyclop:
    skip-tests: true
  depguard:
    rules:
      main:
        list-mode: strict
        files:
          - "$all"
          - "!$test"
          - "!**/crypt/agecrypt/*"
          - "!**/encoding/**/*"
        allow:
          - "$gostd"
          - "github.com/justenwalker/mack"
      tests:
        list-mode: strict
        files:
          - "$test"
          - "!**/crypt/agecrypt/*"
          - "!**/encoding/**/*"
        allow:
          - "$gostd"
          - "github.com/justenwalker/mack"
          - "go.uber.org/mock"
          - "github.com/google/go-cmp/cmp"
      encoding:
        list-mode: strict
        files:
          - "!$test"
          - "**/encoding/**/*"
        allow:
          - "$gostd"
          - "github.com/justenwalker/mack"
          - "github.com/vmihailenco/msgpack/v5"
      agecrypt:
        list-mode: strict
        files:
          - "!$test"
          - "**/crypt/agecrypt/*"
        allow:
          - "$gostd"
          - "filippo.io/age"
          - "github.com/justenwalker/mack/exchange"
run:
  modules-download-mode: readonly
  go: 1.21
output:
  formats:
    - format: checkstyle
      path: lint-report.checkstyle.xml
    - format: colored-line-number
      path: stdout
  sort-results: true
  sort-order:
    - file
    - linter
    - severity