issues:
  exclude-dirs:
    - 'example/.*'
  exclude: []
  exclude-rules:
    - path: internal/testhelpers/random.go
      linters:
        - gochecknoglobals
        - gochecknoinits
        - gosec
    - path: internal/testhelpers/testhelpers.go
      linters:
        - gochecknoglobals
    - path: sensible/encrypt_.*.go
      linters:
        - gochecknoglobals
      source: 'decryptFunc'
    - path: sensible/encrypt_.*.go
      linters:
        - gochecknoglobals
      source: 'encryptFunc'
    - path: sensible/sensible.go
      linters:
        - gochecknoglobals
      source: scheme
    - path: encoding/libmacaroon/.*
      linters:
        - gocyclo
        - cyclop
    - path: .*_test.go
      linters:
        - gocognit
        - gocyclo
        - maintidx
linters:
  enable-all: true
  disable:
    - err113
    - exhaustruct
    - funlen
    - gci
    - mnd
    - intrange
    - lll
    - tenv
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  cyclop:
    skip-tests: true
  depguard:
    rules:
      main:
        list-mode: strict
        files:
          - "$all"
          - "!$test"
        allow:
          - "$gostd"
          - "github.com/justenwalker/mack"
      tests:
        list-mode: strict
        files:
          - "$test"
        allow:
          - "$gostd"
          - "github.com/justenwalker/mack"
          - "github.com/google/go-cmp/cmp"
          - "github.com/sebdah/goldie/v2"
run:
  modules-download-mode: readonly
  go: '1.24'
output:
  formats:
    - format: checkstyle
      path: lint-report.checkstyle.xml
    - format: colored-line-number
      path: stdout
  sort-results: true
  sort-order:
    - file
    - linter
    - severity