services:
  protogen:
    build:
      context: "."
    working_dir: "/gosrc"
    volumes:
      - "../:/gosrc"
    command:
      - bash
      - -c
      - >-
        protoc
        -I=/gosrc/encoding/proto/pb
        --go_out=/gosrc --go_opt=module=github.com/justenwalker/mack
        --go-grpc_out=/gosrc --go-grpc_opt=module=github.com/justenwalker/mack
        /gosrc/encoding/proto/pb/*.proto
