// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: macaroon.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Macaroons []*Macaroon `protobuf:"bytes,1,rep,name=macaroons,proto3" json:"macaroons,omitempty"`
}

func (x *Stack) Reset() {
	*x = Stack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_macaroon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stack) ProtoMessage() {}

func (x *Stack) ProtoReflect() protoreflect.Message {
	mi := &file_macaroon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stack.ProtoReflect.Descriptor instead.
func (*Stack) Descriptor() ([]byte, []int) {
	return file_macaroon_proto_rawDescGZIP(), []int{0}
}

func (x *Stack) GetMacaroons() []*Macaroon {
	if x != nil {
		return x.Macaroons
	}
	return nil
}

type Macaroon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loc     string    `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	Id      []byte    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Caveats []*Caveat `protobuf:"bytes,3,rep,name=caveats,proto3" json:"caveats,omitempty"`
	Sig     []byte    `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *Macaroon) Reset() {
	*x = Macaroon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_macaroon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Macaroon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Macaroon) ProtoMessage() {}

func (x *Macaroon) ProtoReflect() protoreflect.Message {
	mi := &file_macaroon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Macaroon.ProtoReflect.Descriptor instead.
func (*Macaroon) Descriptor() ([]byte, []int) {
	return file_macaroon_proto_rawDescGZIP(), []int{1}
}

func (x *Macaroon) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *Macaroon) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Macaroon) GetCaveats() []*Caveat {
	if x != nil {
		return x.Caveats
	}
	return nil
}

func (x *Macaroon) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Caveat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Vid []byte `protobuf:"bytes,2,opt,name=vid,proto3" json:"vid,omitempty"`
	Cl  string `protobuf:"bytes,3,opt,name=cl,proto3" json:"cl,omitempty"`
}

func (x *Caveat) Reset() {
	*x = Caveat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_macaroon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Caveat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caveat) ProtoMessage() {}

func (x *Caveat) ProtoReflect() protoreflect.Message {
	mi := &file_macaroon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caveat.ProtoReflect.Descriptor instead.
func (*Caveat) Descriptor() ([]byte, []int) {
	return file_macaroon_proto_rawDescGZIP(), []int{2}
}

func (x *Caveat) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *Caveat) GetVid() []byte {
	if x != nil {
		return x.Vid
	}
	return nil
}

func (x *Caveat) GetCl() string {
	if x != nil {
		return x.Cl
	}
	return ""
}

var File_macaroon_proto protoreflect.FileDescriptor

var file_macaroon_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x6d, 0x61, 0x63, 0x6b, 0x2e, 0x6d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x22, 0x41, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x6d,
	0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x61, 0x63, 0x6b, 0x2e, 0x6d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x61,
	0x72, 0x6f, 0x6f, 0x6e, 0x73, 0x22, 0x72, 0x0a, 0x08, 0x4d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6c, 0x6f, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x61, 0x76, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x63, 0x6b, 0x2e, 0x6d, 0x61, 0x63, 0x61,
	0x72, 0x6f, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x76, 0x65, 0x61, 0x74, 0x52, 0x07,
	0x63, 0x61, 0x76, 0x65, 0x61, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x3c, 0x0a, 0x06, 0x43, 0x61, 0x76,
	0x65, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x6c, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74, 0x65, 0x6e, 0x77, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x2f, 0x6d, 0x61, 0x63, 0x6b, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_macaroon_proto_rawDescOnce sync.Once
	file_macaroon_proto_rawDescData = file_macaroon_proto_rawDesc
)

func file_macaroon_proto_rawDescGZIP() []byte {
	file_macaroon_proto_rawDescOnce.Do(func() {
		file_macaroon_proto_rawDescData = protoimpl.X.CompressGZIP(file_macaroon_proto_rawDescData)
	})
	return file_macaroon_proto_rawDescData
}

var file_macaroon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_macaroon_proto_goTypes = []interface{}{
	(*Stack)(nil),    // 0: mack.macaroon.v1.Stack
	(*Macaroon)(nil), // 1: mack.macaroon.v1.Macaroon
	(*Caveat)(nil),   // 2: mack.macaroon.v1.Caveat
}
var file_macaroon_proto_depIdxs = []int32{
	1, // 0: mack.macaroon.v1.Stack.macaroons:type_name -> mack.macaroon.v1.Macaroon
	2, // 1: mack.macaroon.v1.Macaroon.caveats:type_name -> mack.macaroon.v1.Caveat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_macaroon_proto_init() }
func file_macaroon_proto_init() {
	if File_macaroon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_macaroon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_macaroon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Macaroon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_macaroon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Caveat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_macaroon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_macaroon_proto_goTypes,
		DependencyIndexes: file_macaroon_proto_depIdxs,
		MessageInfos:      file_macaroon_proto_msgTypes,
	}.Build()
	File_macaroon_proto = out.File
	file_macaroon_proto_rawDesc = nil
	file_macaroon_proto_goTypes = nil
	file_macaroon_proto_depIdxs = nil
}
